id = "ez"
name = "EZ"
version = "0.3.1"
schema_version = 1
description = "Syntax highlighting and language server for the EZ programming language"
repository = "https://github.com/SchoolyB/EZ"
authors = ["Marshall Burns"]
languages = ["languages/ez"]

[grammars.ez]
repository = "https://github.com/SchoolyB/tree-sitter-ez"
rev = "1738aaec7425315eeba61ad1a7ca4b312283e91a"

[language_servers.ez-lsp]
language = "EZ"
